# Generated by Django 4.0.4 on 2022-05-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_birthdate_user_currenct_user_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='currenct',
            new_name='currency',
        ),
    ]
